```yml
version: '3'

services:
  backend:
    container_name: farmacia-backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/farmacia

  frontend:
    container_name: farmacia-frontend
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    container_name: farmacia-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
```